### ISSUE TITLE
Cannot access links from main Stats page when Fluid stats is in a sub directory in a wordpress site

### ISSUE THREAD

**Issue by krustymk** [DevelopGravity/Fluid-MC-Stats#14]
Wordpress site is in root
Fluid stats is in a subdirectory called .... Stats
Link to Stats Index from Wordpress site in the menu (this works)
When looking at the Fluid stats page and clicking a link it goes to a blank page, ive managed to get a 404 artical not found by changing the permalink settings in wordpress but thats it.. 
Anyway, i would guess Fluid is not overiding wordpress link settings, but thats just a guess...

**Comment by ZacharyDuBois** [comment]
Should be fixed now :)
