### ISSUE TITLE
Server always shows offline

### ISSUE THREAD

**Issue by sshadow** [DevelopGravity/Fluid-MC-Stats#20]
In the newest release from BD our server is always showing offline. I have triple checked the config and all is good. Database functions and all that work great. Our server runs on a bungee network however I wouldn't think that would effect the online/offline status as it "usually" works elsewhere.

Thanks.

**Comment by sshadow** [comment]
string(39) "/home/mcempire/public_html/forum/stats/" bool(true)

**Comment by ZacharyDuBois** [comment]
Hmm, there should be two `bool(true)`s Are you sure you copied all the lines?

**Comment by sshadow** [comment]
Oops my bad. 

string(39) "/home/mcempire/public_html/forum/stats/" bool(true) bool(true)

**Comment by ZacharyDuBois** [comment]
I just entered the IP you have listed on your site into the demo installation, it is also reporting offline and is not having errors. But it is not your Minecraft server because it is responding to DInnerbone's query checker. Let me look into this some more.

**Comment by ZacharyDuBois** [comment]
Hmm, I was just able to use it on another bungee server. So it isn't that. Are you running anything that could be restricting the server query or such? I am clueless right now. I am not very familiar with the Minecraft server query protocol. That is why we use a library for it and that isn't even detecting your server. Sec, I will look a bit more.

**Comment by ZacharyDuBois** [comment]
In your Bungee server's `config.yml` can you make sure `query_enabled` is set to `true` and that `query_port` is set to `25565`. I am out of ideas. 

If that doesn't fix it, I will look deeper in after New Years. Hope you enjoy 2015 :)

**Comment by sshadow** [comment]
Yep they are both set. I will see if I can find some sort of standalone script to test. I know I have seen a few out there in the past. That way we can see for sure if it's just in my hosting environment.

**Comment by sshadow** [comment]
Oh and hope you have a great 2015 as well. Thanks for the help :)

**Comment by ZacharyDuBois** [comment]
Oh, if you want to try with the library we use with Fluid MC Stats, we use [FunnyItsElmo/PHP-Minecraft-Server-Status-Query](https://github.com/FunnyItsElmo/PHP-Minecraft-Server-Status-Query)

If you do figure this out before I do, please share so it is included in the next release :)

**Comment by sshadow** [comment]
Ok I have uploaded your example here and configured it and it's not working http://mcempire.net/forum/serverping/example.php - Will continue to fiddle with it to see if I can get it to detect our server.

I uploaded another I found here and it seems to be working http://mcempire.net/forum/serverping3/view.php - The github link is on that page.

**Comment by ZacharyDuBois** [comment]
Interesting. I luckily with how I wrote the query cache script, this is almost as simple as a drop and replace. But maybe I could open an issue to see if the current library could be fixed. I will do that, and if I don't get a response in a few days, I will go on and use the other one. The problem with the other one is, it does not receive the server icon.

**Comment by ZacharyDuBois** [comment]
@sshadow, I am going to give another day or two for a response on the issue. If no reply, I switch it over to the one you linked :)

**Comment by sshadow** [comment]
Ok thanks for the update :)

**Comment by ZacharyDuBois** [comment]
@sshadow I've gotten no response from him. I will make way with the new script :)

**Comment by ZacharyDuBois** [comment]
I wouldn't say it is ready for use right now as I have not heavily tested it yet. But it has been added :)

**Comment by ZacharyDuBois** [comment]
@sshadow, I did fix it and I randomly went on a server list and tested it with 25 servers at random. I did run into an issue described in #30 and added a workaround. Test out the master branch and let me know how it goes. Also, when you do that and everything works (or doesn't), post back here with a copy of the debug info (Set `$debug` to `true` in the config). Thanks!

**Comment by sshadow** [comment]
Grabbing now to test. Sorry for the delay had a "fun" DDOS issue to work out :(

**Comment by sshadow** [comment]
Ok looks good. My debug info is below. Also I have a theory on why the query may not work on some servers. From the file it looks like it works on the UDP protocol. This worked before my "fun" experience I referenced above however now it is giving me errors as well. The change was me switching over to a DDOS protected IP however it only allows TCP from what I understand. Regardless atleast it shows us online now :) Thanks for that!

```json
{
    "serverInfo": {
        "phpVersion": "5.4.16",
        "webServer": "Apache\/2.2.15",
        "os": "Linux",
        "serverName": "mcempire.net",
        "requestURI": "\/forum\/stats\/",
        "jsonEnabled": true,
        "mysqliEnabled": true
    },
    "configData": {
        "serverIP": "mc.mcempire.net",
        "serverPort": "25565",
        "cdnURI": "",
        "baseURI": "forum\/stats\/",
        "avatarURI": "https:\/\/minotar.net\/avatar\/",
        "customLinks": {
            "MCEmpire Forum": "http:\/\/mcempire.net\/forum\/"
        },
        "topStatCalType": "",
        "numberOfTopPlayer": "",
        "hideLimitedWarning": false
    },
    "envInfo": {
        "APPPATH": "\/home\/mcempire\/public_html\/forum\/stats\/",
        "LINKBASE": "\/forum\/stats\/",
        "fmcsVersion": "MASTER"
    },
    "fileInfo": {
        "tmpDirExits": true,
        "tmpDirWrite": true,
        "configExits": true,
        "configWrite": true,
        "installExists": false,
        "queryCacheFileExists": true,
        "queryCacheFileWrite": true
    },
    "otherInfo": {
        "queryData": {
            "mcQuery": {
                "getInfo": false,
                "getPlayers": false
            },
            "mcPing": {
                "query": {
                    "version": {
                        "name": "BungeeCord 1.8",
                        "protocol": 4
                    },
                    "players": {
                        "max": 500,
                        "online": 2
                    },
                    "description": "\u00a7dMCEmpire Resurrected",
                    "modinfo": {
                        "type": "FML",
                        "modList": [

                        ]
                    }
                }
            },
            "pingTimes": {
                "queryPing": 2050,
                "pingPing": 233,
                "avgPing": 1142
            },
            "lastUpdate": "2015-01-13 06:41:36"
        }
    }
}
```

**Comment by ZacharyDuBois** [comment]
Eh. I have no idea why people DDoS but it happens. Great to here you got this sorted out. :) I will test that theory later today. If that's the case, I can update the docs with that information :D
