### ISSUE TITLE
Tighter integration of Dynmap

### ISSUE THREAD

**Issue by djjaeger82** [DevelopGravity/Fluid-MC-Stats#34]
Great plugin, but it would be great if you can enable tighter integration of dynmap into this plugin.  Perhaps making a Map link in the very top of the fixed menu?  (you could ask for the URL to the dynmap server in the initial config and link it).  Not sure if you could put a snapshot img of the default world somewhere on the homepage too or not.  (I think WebStatsX might have done something like that but honestly its been a while and I can't remember).  Thanks!!

**Comment by ZacharyDuBois** [comment]
I can add a map page fairly easily with an iframe that has the map in it (I think that is how WebStatsX did it). But I can one up this. I could also make the entire background work as the map (I've see this done on a lot of cool sites before).

**Comment by djjaeger82** [comment]
That sounds really cool!   Can't wait to check it out, let me know if I can be of any use in testing.   I have a relatively low use 5 person or so server with my friends but that also makes it extremely easy for me to test out new stuff at will.

**Comment by ZacharyDuBois** [comment]
I will probably have a working copy tomorrow that will have it. I am exhausted today (That and it is 23:44 here). I don't have Overviewer or Dynmap anymore so I will need to probably set one of them up soon. Resource-wise, Overviewer has a better outcome so I will probably get that setup tomorrow too.

**Comment by ZacharyDuBois** [comment]
@djjaeger82, let me know what you think of the current source (Run a test site or something :) ) That doesn't contain the background yet. Just this: 

![screen shot 2015-01-16 at 9 41 34 pm](https://cloud.githubusercontent.com/assets/2458289/5787333/7a4eb8b4-9dc8-11e4-899f-8f99821c48d9.png)
![screen shot 2015-01-16 at 9 39 32 pm](https://cloud.githubusercontent.com/assets/2458289/5787334/7a5d2de0-9dc8-11e4-8c7f-326833dae01a.png)

**Comment by ZacharyDuBois** [comment]
That commit should add a background for it too. Try these out and let me know how you like them. The current UI doesn't provide a lot of room on the actual map page to do a ton, that is why I added the link to the full map.

**Comment by djjaeger82** [comment]
Thanks this looks pretty good actually.  The map integration in the link at the top, and having it available as a sub "frame" in your GUI is exactly what I had in mind, also nice you have the link to open it full screen if you want.  Not sure if I really like the background option though, the other elements of the GUI are just too big to really make it useful, but still kind of neat.  Thanks again!

**Comment by ZacharyDuBois** [comment]
No problem. I think I need to fix the background so it will strip out all the map controls. I have it currently so you can't move it in the background but, it'd be good to get rid of the UI too.
