### ISSUE TITLE
Make Player List Ordering Configurable

### ISSUE THREAD

**Issue by krustymk** [DevelopGravity/Fluid-MC-Stats#36]
Can you make it so they can be sorted either by alphabet or time descending or ascending? 
Just an idea

Cheers, great job by the way!

**Comment by ZacharyDuBois** [comment]
Requests are welcome, I want the v0.2.1 release to be a big one before the pause between it and the new UI coming in v0.3.0 :)

**Comment by ZacharyDuBois** [comment]
Working on this now ;)

**Comment by ZacharyDuBois** [comment]
@krustymk, Do you want the 2nd column to change to what stat you tell it to sort by? Or keep it playtime?

**Comment by ZacharyDuBois** [comment]
@krustymk, I think that is what you are looking for :)
