### ISSUE TITLE
Top players page isn't working

### ISSUE THREAD

**Issue by Robin222** [DevelopGravity/Fluid-MC-Stats#39]
I get this error on the top players page 

Unknown column 'kills' in 'field list'
![untitled](https://cloud.githubusercontent.com/assets/8219209/5793231/73c482c6-9ef9-11e4-8c6b-04f03325c86b.png)

How do i fix it?

**Comment by ZacharyDuBois** [comment]
Sorry about the tag spam. My iPad dropped connection. Could you please follow the format in the Contributing file?

**Comment by Robin222** [comment]
I turned the debug mode on and i got this error:

YOU ARE IN DEBUG MODE! FLUID MC STATS WILL NOT FUNCTION WHEN IN THIS MODE!
Paste the following into your issue on GitHub:

``` json
<br><table border='1' cellpadding='2' bgcolor='#FFFFDF' bordercolor='#E8B900' align='center'><tr><td><font face='Arial' size='1' color='#000000'><b>PHP Error Message</b></font></td></tr></table><br />
<b>Warning</b>:  json_encode() expects exactly 1 parameter, 2 given in <b>/home/a7066133/public_html/inc/debug.php</b> on line <b>61</b><br />
<br><table border='1' cellpadding='2' bgcolor='#FFFFDF' bordercolor='#E8B900' align='center'><tr><td><div align='center'><a href='http://www.000webhost.com/'><font face='Arial' size='1' color='#000000'>Free Web Hosting</font></a></div></td></tr></table>
```

**Comment by ZacharyDuBois** [comment]
Create a file on your server called `info.php` with the following contents:

``` php
<?php
echo PHP_VERSION;
```

That error is normally thrown when you have a PHP version prior to 5.3 because it does not support the `JSON_PRETTY_PRINT` parameter.

**Comment by Robin222** [comment]
Alright thanks!

**Comment by Robin222** [comment]
Do i leave it on debug mode: true? or false?

Because i already uploaded the file but i keep getting the error

**Comment by ZacharyDuBois** [comment]
You have to load `domain.tld/info.php` once you uploaded it.

**Comment by Robin222** [comment]
Wait hold on am getting confused, do i just type domain.tld/info.php on the info.php? sorry am not very good at this.

**Comment by ZacharyDuBois** [comment]
Load in a web browser `domain.tld/info.php`. Your screenshot shows `pvpworldstats.site88.net` so load `http://pvpworldstats.site88.net/info.php` and it should just say the version of PHP you are running.

**Comment by Robin222** [comment]
```
PHP Error Message

Warning: include_once(/home/a7066133/public_html/pages/info.php.php) [function.include-once]: failed to open stream: No such file or directory in /home/a7066133/public_html/index.php on line 73

Free Web Hosting

PHP Error Message

Warning: include_once() [function.include]: Failed opening '/home/a7066133/public_html/pages/info.php.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/a7066133/public_html/index.php on line 73

Free Web Hosting
```

**Comment by ZacharyDuBois** [comment]
Then you have something wonky going on with the hosting provider, I am more than happy to help you get it working but, I am not sure if I can't even get any information as to what the hosting service you are using is running on their systems.

**Comment by Robin222** [comment]
Ok thanks.

**Comment by Robin222** [comment]
What web hosting do you recommend me?

I was using 000webshost for the website

**Comment by ZacharyDuBois** [comment]
I recommend using a VPS. You can get one for $5 over at DigitalOcean. But, I don't think you would be able to run it to be honest. You could go for a shared host at GoDaddy or someone for it. Hosting providers are a dime a dozen.

**Comment by ZacharyDuBois** [comment]
Closing.

**Comment by adamwbb** [comment]
simple fix
open config.php in a editor replace "kills" with "kill" save file.
works for me every time.

**Comment by ZacharyDuBois** [comment]
@adamwbb, his problem is he doesn't have JSON support because he cannot even render the JSON debug page.
