### ISSUE TITLE
Mysql Efficiency Issue

### ISSUE THREAD

**Issue by jessefjxm** [DevelopGravity/Fluid-MC-Stats#41]
There seems to have some serious mysql efficiency issue with Stats 2.0.1 with newest spigot 1.8 snapshot…… 

I built a test server using newest spigot 1.8 snapshot with only Stats 2.0.1 & vault installed, and 1 player. 
CPU% of mysql thread in htop keep 0~1.6 when no players in test server.
CPU% rises to 90~100% 1s after I logged in.Falls to normal after 5s.
CPU% also rises 5s after I break/place several blocks.Falls to normal after 5s.
No significant changes when I logout test server. But when testing in another server with several plugins, CPU% also rises after I left.

Hope there's a way to fix it :)

**Comment by ZacharyDuBois** [comment]
This repository is not for the Stats plugin. (Also, I do not have is issue so it is probably something with your setup. )
