### ISSUE TITLE
WebSite-Fluid-MC-Stats Issues

### ISSUE THREAD

**Issue by KreatorB** [DevelopGravity/Fluid-MC-Stats#42]
Hello, thanks for the awesome work and great server addons.
I am having a few issues since trying to install the Fluid-MC-Stats.
1. It is so slow and hangs, is there a reason and how can I adjust or fix this........
2. After several install to resolve speed issue I noticed it always says my server is offline, yet the database it calling and the MYSQL test was successful when going through the steps of install!

If you like visit it at http://www.iplayablockhead.com/mcstats/

Thank you
K

**Comment by ZacharyDuBois** [comment]
Could you please follow the information provided in the `CONTRIBUTING.md` file? Thanks.

**Comment by KreatorB** [comment]
- Fluid MC Stats Version: Beta v0.2.0
  - Stats Version: v2.0.1
  - Site URL: http://www.iplayablockhead.com/mcstats/
  
  ### Issue:
  
  I am having a few issues since trying to install the Fluid-MC-Stats.
  1. It is so slow and hangs, is there a reason and how can I adjust or fix this........
  2. After several install to resolve speed issue I noticed it always says my server is offline, yet the database it calling and the MYSQL test was successful when going through the steps of install!
  3. Playtime not recording any playtime to database/
  
  ### Expected Behavior:
  
  1.Should load details in a few secs not minutes
  2. Show online status
  3. Should count time played!

**Comment by ZacharyDuBois** [comment]
I need to see the debug information specified in that file.

**Comment by KreatorB** [comment]
how do I get you the debug info? I am happy to provide, but have no clue what you are looking for?
I did a debug on myself and got this in the console!

```
30.03 15:46:57 [Server] INFO [Debug]      data: 
30.03 15:46:57 [Server] INFO [Debug]    type: Shear
30.03 15:46:57 [Server] INFO [Debug]        vars: [] CurrentValue: 0.0
30.03 15:46:57 [Server] INFO [Debug]        vars: [] UpdateValue: 0.0
30.03 15:46:57 [Server] INFO [Debug]      data: 
30.03 15:46:57 [Server] INFO [Debug]    type: Itemdrops
30.03 15:46:57 [Server] INFO [Debug]        vars: [] CurrentValue: 0.0
30.03 15:46:57 [Server] INFO [Debug]        vars: [] UpdateValue: 0.0
30.03 15:46:57 [Server] INFO [Debug]      data: 
30.03 15:46:57 [Server] INFO [Debug]    type: PVPStreak
30.03 15:46:57 [Server] INFO [Debug]        vars: [] CurrentValue: 0.0
30.03 15:46:57 [Server] INFO [Debug]        vars: [] UpdateValue: 0.0
30.03 15:46:57 [Server] INFO [Debug]      data: 
30.03 15:46:57 [Server] INFO [Debug]    type: Playtime
30.03 15:46:57 [Server] INFO [Debug]        vars: [] CurrentValue: 0.0
30.03 15:46:57 [Server] INFO [Debug]        vars: [] UpdateValue: 0.0
30.03 15:46:57 [Server] INFO [Debug]      data: 
30.03 15:46:57 [Server] INFO [Debug]    type: On fire
30.03 15:46:57 [Server] INFO [Debug]        vars: [] CurrentValue: 0.0
30.03 15:46:57 [Server] INFO [Debug]        vars: [] UpdateValue: 0.0
30.03 15:46:57 [Server] INFO [Debug]      data: 
30.03 15:46:57 [Server] INFO [Debug]    type: Omnomnom
30.03 15:46:57 [Server] INFO [Debug]        vars: [] CurrentValue: 0.0
30.03 15:46:57 [Server] INFO [Debug]        vars: [] UpdateValue: 0.0
30.03 15:46:57 [Server] INFO [Debug]      data: 
30.03 15:46:57 [Server] INFO [Debug]    type: Money
30.03 15:46:57 [Server] INFO [Debug]  world: sax2
30.03 15:46:57 [Server] INFO [Debug] Stats ------------
```

I did note that the world is not correct, it should say world, sax2 is one of the 4 worlds on the server

**Comment by ZacharyDuBois** [comment]
It says in the `CONTRIBUTING.md` file.

**Comment by KreatorB** [comment]
this is what is in the CONTRIBUTING.md file.

# Contributing

## Rules
- Do not assign a milestone, we will do that after reviewing.
- Do not assign to someone, we will do that.
- Do not spam comment.
- Do not bump issues.
- Make sure you are using the latest version of both, the plugin and interface.
- Attach images of the errors.
- Copy the error text if any.

If you want to make issues and help us out, please follow this template to speed things up.

```
- Fluid MC Stats Version: Beta v0.X.X
- Stats Version: v2.X.X
- Site URL: http://domain.tld

### Issue:

Blah Blah Blah

###  Expected Behavior:

How I think it should work.
```

**Comment by ZacharyDuBois** [comment]
Ah, use the source version from this repo.

**Comment by ZacharyDuBois** [comment]
The interface it not part of the Minecraft server at all making those logs irrelevant.

**Comment by KreatorB** [comment]
Okay, I changed config file so Debug: true and reloaded my Site (slow as hell) and it changed nothing.

**Comment by KreatorB** [comment]
you keep telling me to look at what needs to be done, I did the following like it states.
Open config.php and set debug to true. Then load Fluid MC Stats in your browser. It should say YOU ARE IN DEBUG MODE! FLUID MC STATS WILL NOT FUNCTION WHEN IN THIS MODE!. Paste the information it tells you.

I hate to tell you the Stats plugin is still working in debug mode after I set it to true and restarted the server to make sure. NOT to mention when I load the webstie Fuild-MC-Stats in the browser it does not change anything....

Now if you can give me a Step by Step to Help I will do it. But thus far you have not told me anything that was not written and even helpful as it all did not lead me right back in a circle.

I understand standards and why we have them but even your troubleshooting is not help me. I have looked it over a few times.

CAN YOU HELP?

**Comment by ZacharyDuBois** [comment]
1. Download the master branch.
2. See if the issue still occurs after installing the master.
3. If the issue still occurs, turn on debug and paste the information it will provide.
4. Report back here.

**Comment by KreatorB** [comment]
Okay did all that and now it is completely different the problem.
It loads the Fluid page but not the links like player and I get with a 404error

**Comment by ZacharyDuBois** [comment]
You didn't copy the htaccess file.

**Comment by KreatorB** [comment]
I replaced it all and reinstalled using the Master

**Comment by KreatorB** [comment]
I rebooted server with DeBug on and I get nothin on the Fluid-Site in terms of bugs or codes I can give you

**Comment by ZacharyDuBois** [comment]
Please increase your skills with running a server before opening an issue. I cannot baby users through the setup steps.

**Comment by KreatorB** [comment]
[Deleted by @ZacharyDuBois]

**Comment by ZacharyDuBois** [comment]
Sorry, I don't waste time trying to baby someone who doesn't know how to host the simplest of sites.
