### ISSUE TITLE
Not Found 

### ISSUE THREAD

**Issue by doomlordking** [DevelopGravity/Fluid-MC-Stats#44]
i installed Fluid-MC-Stats 2.0 fine but when i click any links it give me a not found error. "Not Found
The requested URL /stats/live-ticker was not found on this server."   Stats v2.0.1 f

**Comment by ZacharyDuBois** [comment]
Please use the format provided in the contributing file.

**Comment by ZacharyDuBois** [comment]
Closed for inactivity.
