### ISSUE TITLE
Server status offline?

### ISSUE THREAD

**Issue by gerardvanschip** [DevelopGravity/Fluid-MC-Stats#46]
My server is located at mc.kaizen-worlds.net:26988 which I configured, both as address and port and the whole thing. My Wordpress plugin has the same details and understands that my server is up but stats seems to think its off.

**Comment by ZacharyDuBois** [comment]
Could you please follow the contributing file.

**Comment by ZacharyDuBois** [comment]
Closed for inactivity.
