### ISSUE TITLE
json_encode() Error

### ISSUE THREAD

**Issue by cronoszeu** [DevelopGravity/Fluid-MC-Stats#48]
- Fluid MC Stats Version: Beta vv0.2.0
- Stats Version: v2.0.1
- Site URL: http://vanillasurvival.com/
### Issue:

Right side wont show ... 
### Expected Behavior:

To show server stats ?
### Debug Output:

YOU ARE IN DEBUG MODE! FLUID MC STATS WILL NOT FUNCTION WHEN IN THIS MODE!
Paste the following into your issue on GitHub:

``` json
<br />
<b>Warning</b>:  json_encode() expects exactly 1 parameter, 2 given in <b>C:\AppServ\www\vanillasurvival.com\inc\debug.php</b> on line <b>65</b><br />

```

**Comment by cronoszeu** [comment]
PHP info
http://vanillasurvival.com/phpinfo.php

Also config.php for server
// Your Minecraft server name.
$server_name = 'Vanilla Survival';
// An A Record, AAAA Record, CNAME Record or IP to your Minecraft server without the port.
$mc_server_ip = 'vanillasurvival.com';
// Port Number to your Minecraft server.
$mc_server_port = '25565';
// A 'nice' address for your Minecraft server. This will be the address that is displayed on the web interface.
$mc_server_disp_addr = 'vanillasurvival.com';
// The URL to a custom image to use as the server icon. If not set, we will use the server-icon.png on your Minecraft server.
$mc_custom_icon = 'server-icon.png';

**Comment by ZacharyDuBois** [comment]
Hi @cronoszeu. So if you haven't noticed, this project has been discontinued until I can find the time to update it. But I am happy to help you out with your issue. It appears you're running an old version of PHP which cannot use the `JSON_PRETTY_PRINT` parameter. All you need to do to get rid of that error is do `cd /where/fmcs/is/installed && grep -R JSON_PRETTY_PRINT *` to find where all the files that use that parameter and remove it (including the comma). If I remember correctly, `inc/debug.php` and `inc/status-cache.php` are the only files that use it.

From `inc/debug.php` change L65 to look like the following. I have included the surrounding lines to help you find it.

`````` php
echo "Paste the following into your issue on GitHub:\n```json\n";
echo json_encode($output, JSON_PRETTY_PRINT);
echo "\n```";
``````

And from `inc/status-cache.php` on L102:

``` php
  $fp = fopen($cacheFile, 'w');
  fwrite($fp, json_encode($rdata, JSON_PRETTY_PRINT));
  fclose($fp);
```

Let me know how that goes for you! :)

**Comment by cronoszeu** [comment]
Ah I did not know is not any more supported as it can be a nice website integrated with a cms will do the job :)

I have done that and this is the result

YOU ARE IN DEBUG MODE! FLUID MC STATS WILL NOT FUNCTION WHEN IN THIS MODE!
Paste the following into your issue on GitHub:

``` json
{  
  "serverInfo":{  
    "phpVersion":"5.2.6",
    "webServer":"Apache\/2.2.8 (Win32) PHP\/5.2.6",
    "os":"WINNT",
    "serverName":"vanillasurvival.com",
    "requestURI":"\/",
    "jsonEnabled":true,
    "mysqliEnabled":true
  },
  "configData":{  
    "serverIP":"vanillasurvival.com",
    "serverPort":"25565",
    "cdnURI":"",
    "baseURI":"",
    "avatarURI":"http:\/\/cravatar.eu\/avatar\/",
    "customLinks":{  
      "Develop Gravity":"http:\/\/developgravity.com\/",
      "Lolmewn":"http:\/\/lolmewn.nl\/",
      "Mojang":"http:\/\/mojang.com\/"
    },
    "topStatCalType":"playtime",
    "numberOfTopPlayer":10,
    "hideLimitedWarning":false,
    "mapURL":"",
    "mapBg":false,
    "playerListSort":"online",
    "playerListOrder":"descending"
  },
  "envInfo":{  
    "APPPATH":"C:\\AppServ\\www\\vanillasurvival.com\/",
    "LINKBASE":"\/",
    "fmcsVersion":"MASTER"
  },
  "fileInfo":{  
    "tmpDirExits":true,
    "tmpDirWrite":true,
    "configExits":true,
    "configWrite":true,
    "installExists":false,
    "queryCacheFileExists":false,
    "queryCacheFileWrite":false
  },
  "otherInfo":{  
    "queryData":"No Cache File"
  }
}
```

I think the prob is the cache file or something no idea how to fix it.
Any bit of help will help :)

Regards

**Comment by ZacharyDuBois** [comment]
@cronoszeu Awesome. I do plan to work on this again soon but I have to get some other things done first. And yes, the query cache appears to be the last problem. I've gone ahead and formatted that JSON you posted so it is easier to read. As you can see, `"queryCacheFileWrite":false`. All you need to do is change that temporary directory so it can be written to by the web user.

**Comment by cronoszeu** [comment]
Hi,

Well is what I tried to do after I saw the problem but I had no luck ..
I run my webhost on a win server 2008 R2 with appserv installed ... From what I read is that windows has by default permission to allow writings ..

The problem looks it is inc/status-cache.php
If I disable this in serverstatusui.php the right side will show but say server online but than
MOTD:
Version:
Players: of max

If you got any idea let me know.
Even the check it say:
"tmpDirWrite":true,

Regards

**Comment by ZacharyDuBois** [comment]
Very odd. Then again, this isn't I planned to support Windows for (As stated in the README.md). If the web user can write to that temp directory but for some reason cannot create the file for the query cache, it seems like it is a permissions problem. Windows permissions are different than a UNIX-like system. I recommend you grab a linux server over at [DigitalOcean](https://we.destroy.tokyo/DigitalOcean) ($10 ref) and run it there. Honestly, I was talking with my friend the other day about the usefulness of a Windows server and we could only think of things to relate to Microsoft products, other than that, beats it.

**Comment by cronoszeu** [comment]
I know what you but I will prefer to have it on my server as with my mc server (a 24GB dedi)
I will check more and see if I find a solution

Regards

**Comment by cronoszeu** [comment]
There

YOU ARE IN DEBUG MODE! FLUID MC STATS WILL NOT FUNCTION WHEN IN THIS MODE!
Paste the following into your issue on GitHub:

``` json
{
    "serverInfo": {
        "phpVersion": "5.5.12",
        "webServer": "Apache\/2.4.9 (Win64) PHP\/5.5.12",
        "os": "WINNT",
        "serverName": "vanillasurvival.com",
        "requestURI": "\/",
        "jsonEnabled": true,
        "mysqliEnabled": true
    },
    "configData": {
        "serverIP": "vanillasurvival.com",
        "serverPort": "25565",
        "cdnURI": "",
        "baseURI": "",
        "avatarURI": "http:\/\/cravatar.eu\/avatar\/",
        "customLinks": {
            "Store": "http:\/\/shop.vanillasurvival.com"
        },
        "topStatCalType": "playtime",
        "numberOfTopPlayer": "10",
        "hideLimitedWarning": false,
        "mapURL": "",
        "mapBg": "false",
        "playerListSort": "online",
        "playerListOrder": "desc"
    },
    "envInfo": {
        "APPPATH": "C:\\wamp\\www\/",
        "LINKBASE": "\/",
        "fmcsVersion": "MASTER"
    },
    "fileInfo": {
        "tmpDirExits": true,
        "tmpDirWrite": true,
        "configExits": true,
        "configWrite": true,
        "installExists": false,
        "queryCacheFileExists": true,
        "queryCacheFileWrite": true
    },
    "otherInfo": {
        "queryData": null
    }
}
```

But the website still say server offline :))
Also can I get an example of query.json writings?

Regards

**Comment by cronoszeu** [comment]
Hi,

Ok I done it all works as it should :) and I have no idea how I did it ..

Thanks for help guys and please start again .. this can be a nice free website with premium plugins like admin panel or something

Regards

**Comment by ZacharyDuBois** [comment]
No problem, I am glad I was of help :) I will try to get started on this again in a month or two but no guarantees :/
